import java.util.*;

public class P61_CyclicalFigurateNumbers {
    // Project Euler - Problem 61 - Cyclical figurate numbers
    // Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal)
    // numbers and are generated by the following formulae:
    // Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
    // Square	 	P4,n=n2	 	1, 4, 9, 16, 25, ...
    // Pentagonal	 	P5,n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
    // Hexagonal	 	P6,n=n(2n−1)	 	1, 6, 15, 28, 45, ...
    // Heptagonal	 	P7,n=n(5n−3)/2	 	1, 7, 18, 34, 55, ...
    // Octagonal	 	P8,n=n(3n−2)	 	1, 8, 21, 40, 65, ...
    // The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
    // The set is cyclic, in that the last two digits of each number is the first two digits of the next number
    // (including the last number with the first).
    // Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is
    // represented by a different number in the set.
    // This is the only set of 4-digit numbers with this property.
    // Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type:
    // triangle, square, pentagonal, hexagonal, heptagonal, and octagonal,
    // is represented by a different number in the set.

    public static void main(String[] args) {
        String message = "The sum of the only ordered set of six cyclic 4-digit numbers " +
                "for which each polygonal type: " +
                "triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, " +
                "is represented by a different number in the set is %,d\n" +
                "The set is: %s\n";
        List<int[]> solution = P61_CyclicalFigurateNumbers.getList(6);
        long sum = P61_CyclicalFigurateNumbers.getSum(solution);
        System.out.printf(message, sum, solution.toString());
    }

    private static Polygonal triangular = new Triangular();
    private static Polygonal square = new Square();
    private static Polygonal pentagonal = new Pentagonal();
    private static Polygonal hexagonal = new Hexagonal();
    private static Polygonal heptagonal = new Heptagonal();
    private static Polygonal octagonal = new Octagonal();

    static List<int[]> getList(int size) {
        // iterate through octagonal seeds
        // for each polygonal (3 .. 7): attempt to add one new cyclical polygonal
        // track 1) partial solution, 2) polygonal id (3 .. 7) and 3) n in f(n) to attempt
        // recursive call
        return getList(size, null, 8, 1);
    }

    static List<int[]> getList(int size, List<int[]> partial, int seed, int seedStart) {
        if (size == 1) return makeList(seed, seedStart);
        if (seed < 3) return null;
        while (true) {
            int[] polygonal = new int[]{seed, seedStart};
            if (digitCount(polygonal) > 4) {
                seed++;
                seedStart = 0;
            } else {
                checkSolution(partial, polygonal);
                if (partial == null) {
                    
                }
            }
        }
    }

    private static List<int[]> checkSolution(List<int[]> partial, int[] polygonal) {
        partial.add(polygonal);
        if (isSolution(partial)) return partial;
        return null;
    }

    static boolean isSolution(List<int[]> solution) {
        return false;
    }

    static List<int[]> makeList(int polygonal, int n) {
        List<int[]> list = new ArrayList<>();
        list.add(new int[]{polygonal, n});
        return list;
    }

    static long getSum(List<int[]> list) {
        long sum = 0;
        long value = 0;
        for (int[] item : list) {
            switch (item[0]) {
                case 3:
                    value = triangular.function(item[1]);
                case 4:
                    value = square.function(item[1]);
                case 5:
                    value = pentagonal.function(item[1]);
                case 6:
                    value = hexagonal.function(item[1]);
                case 7:
                    value = heptagonal.function(item[1]);
                case 8:
                    value = octagonal.function(item[1]);
            }
            sum += value;
        }
        return sum;
    }
}
