public class P45_Triangular {
    // Project Euler - Problem 45 - Triangular, pentagonal, and hexagonal
    // Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    // Triangle   Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
    // Pentagonal Pn=n(3n−1)/2  1, 5, 12, 22, 35, ...
    // Hexagonal  Hn=n(2n−1)    1, 6, 15, 28, 45, ...
    // It can be verified that T285 = P165 = H143 = 40755.
    // Find the next triangle number that is also pentagonal and hexagonal.

    public static final int GIVEN = 40755;
    public static Triangular triangular = new Triangular();
    public static Pentagonal pentagonal = new Pentagonal();
    public static Hexagonal hexagonal = new Hexagonal();

    public static void main(String[] args) {
        long next = P45_Triangular.next(GIVEN);
        System.out.printf("The next triangular number after %,d is %,d.\n", GIVEN ,next);
    }

    public P45_Triangular() {
    }

    public static long next(long given) {
        while (!done(given)) {
            if (triangular.current() < pentagonal.current() || triangular.current() < hexagonal.current()) {
                triangular.next();
            } else if (pentagonal.current() < hexagonal.current()) {
                pentagonal.next();
            } else {
                hexagonal.next();
            }
        }
        return triangular.current();
    }

    public static boolean done(long given) {
        return triangular.current() > given &&
                triangular.current() == pentagonal.current() &&
                triangular.current() == hexagonal.current();
    }

    public static void reset() {
        triangular.reset();
        pentagonal.reset();
        hexagonal.reset();
    }
}
